name: nile test and release

on:
  push:
    branches:
    - 287-test

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Add '3.10-dev' once frozendict issue is resolved
        # See https://github.com/starkware-libs/cairo-lang/issues/38
        python_version: [ '3.9' ]
        os: [ubuntu-latest]
    name: ${{ matrix.os }} - Python ${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64
      - run: python -m pip install -U setuptools
      - run: python -m pip install -e .[testing]
      - run: tox -e lint
      - run: tox
